name: Unit_Tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Set up Python 3.14t
      uses: astral-sh/setup-uv@v5
      with:
        python-version: "3.14t"

    - name: Check Python version
      run: |
        uv run python --version
        uv run python -c "import sysconfig; print('Py_GIL_DISABLED =', sysconfig.get_config_var('Py_GIL_DISABLED'))"

    - name: Install dependencies
      run: uv sync --frozen

    - name: Test with pytest
      run: uv run pytest tests --ignore=tests/_old_unit_tests
